# Generated by Django 2.2.6 on 2019-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('picture_url', models.CharField(max_length=1000)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('fcm_token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=80)),
                ('patientID', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=8000)),
                ('picture_url', models.CharField(max_length=1000)),
                ('date_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
